version: "3.7"

services:
  backend_fastapi:
    container_name: backend-fastapi-dev
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backendfastapi/:/usr/src/app/
    ports:
      - 8000:8000
  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn start
    volumes: 
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports: 
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  postgres_data:
  node_modules: