version: "3.7"

services:
  backend_fastapi:
    container_name: backend-fastapi
    build: 
      context: ./backendfastapi
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backendfastapi/:/usr/src/app/
    ports:
      - 8000:8000
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn start
    volumes: 
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports: 
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    container_name: postgresql
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=car_wash
      - POSTGRES_PASSWORD=car_wash
      - POSTGRES_DB=car_wash
volumes:
  postgres_data:
  node_modules: